###
GET http://127.0.0.1:3000/api/v1/astro
Accept: application/json

### GENERAL ###
GET http://127.0.0.1:3000/api/v1/astro/general
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/general/daos?from=1637751850203
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/general/activity?from=1637751850203
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/general/activity/leaderboard
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/general/community.sputnik-dao.near
Accept: application/json

### USERS ###
GET http://127.0.0.1:3000/api/v1/astro/users
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/users/history?from=1637751850203
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/users/leaderboard
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/users/community.sputnik-dao.near
Accept: application/json

###
GET http://127.0.0.1:3000/api/v1/astro/users/community.sputnik-dao.near/history?from=1637751850203
Accept: application/json
