GET http://127.0.0.1:3000/api/v1/astro/activity
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/activity/history
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/activity/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/activity/genesis.sputnik-dao.near
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/activity/genesis.sputnik-dao.near/history
Accept: application/json
