GET http://127.0.0.1:3000/api/v1/astro/daos
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/daos/near-insider.sputnik-dao.near
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/daos/autocomplete/gen
Accept: application/json
