GET http://127.0.0.1:3000/api/v1/astro/general
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/daos
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/active
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/active/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/groups
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/groups/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/average-groups
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/community.sputnik-dao.near
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/community.sputnik-dao.near/activity
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/general/community.sputnik-dao.near/groups
Accept: application/json
