GET http://127.0.0.1:3000/api/v1/astro/tokens
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/fts
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/fts/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/fts-vl
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/fts-vl/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/nfts
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/nfts/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/community.sputnik-dao.near
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/community.sputnik-dao.near/fts
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/community.sputnik-dao.near/fts-vl
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tokens/community.sputnik-dao.near/nfts
Accept: application/json
