GET http://127.0.0.1:3000/api/v1/astro/tvl
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/tvl
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/tvl/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/bounties-and-grants-vl
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/bounties-and-grants-vl/leaderboard
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/vandao.sputnik-dao.near
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/vandao.sputnik-dao.near/tvl
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/vandao.sputnik-dao.near/bounties/number
Accept: application/json
###
GET http://127.0.0.1:3000/api/v1/astro/tvl/vandao.sputnik-dao.near/bounties/vl
Accept: application/json
