export enum DaoStatsMetric {
  DaoCount = 'DAO_COUNT',
  GroupsCount = 'GROUPS_COUNT',
  CouncilSize = 'COUNCIL_SIZE',
  MembersCount = 'MEMBERS_COUNT',
  ProposalsCount = 'PROPOSALS_COUNT',
  ProposalsPayoutCount = 'PROPOSALS_PAYOUT_COUNT',
  ProposalsCouncilMemberCount = 'PROPOSALS_COUNCIL_MEMBER_COUNT',
  ProposalsPolicyChangeCount = 'PROPOSALS_POLICY_CHANGE_COUNT',
  ProposalsInProgressCount = 'PROPOSALS_IN_PROGRESS_COUNT',
  ProposalsApprovedCount = 'PROPOSALS_APPROVED_COUNT',
  ProposalsRejectedCount = 'PROPOSALS_REJECTED_COUNT',
  ProposalsExpiredCount = 'PROPOSALS_EXPIRED_COUNT',
  ProposalsBountyCount = 'PROPOSALS_BOUNTY_COUNT',
  ProposalsMemberCount = 'PROPOSALS_MEMBER_COUNT',
  BountiesCount = 'BOUNTIES_COUNT',
  BountiesValueLocked = 'BOUNTIES_VALUE_LOCKED',
  FtsCount = 'FTS_COUNT',
  NftsCount = 'NFTS_COUNT',
}
