apiVersion: v1
kind: ConfigMap
metadata:
  name: dao-stats-aggregator-configmap
data:
  PORT: "3000"
  NEST_APP_TYPE: aggregator
  AGGREGATOR_POLLING_SCHEDULE: "{{ .Values.environment.aggregator_polling_schedule }}"
  LOG_LEVELS: "log,warn,error"
