apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  PORT: "3000"
  NEST_APP_TYPE: aggregator
  AGGREGATOR_POLLING_SCHEDULE: "{{ .Values.environment.aggregator_polling_schedule }}"
  LOG_LEVELS: "{{ .Values.environment.log_levels }}"
  SODAKI_API_BASE_URL: "{{ .Values.environment.sodaki_api_base_url }}"
  COINGECKO_API_BASE_URL: "{{ .Values.environment.coingecko_api_base_url }}"
  SMART_CONTRACTS: "{{ .Values.environment.smart_contracts }}"
  DATABASE_MIGRATIONS_LIST: "{{ .Values.environment.database_migrations_list }}"
