name: Build Deploy All
on:
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: Specify environment to run on. Valid values are develop, production
  push:
    branches:
    - develop
    - staging
    tags:
    - "**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}

jobs:
  get-environment:
    name: Get Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.get-environment.outputs.environment }}
      namespace_prefix: ${{ steps.get-environment.outputs.namespace_prefix }}
      k8s_ingress_base_host: ${{ steps.get-environment.outputs.k8s_ingress_base_host }}
      kube_config_data_secret_name: ${{ steps.get-environment.outputs.kube_config_data_secret_name }}
    steps:
    - name: get environment
      id: get-environment
      shell: bash
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags.* ]]
        then
          echo "::set-output name=environment::production"
          echo "::set-output name=namespace_prefix::dao-stats-api-production"
          echo "::set-output name=k8s_ingress_base_host::api.daostats.io"
          echo "::set-output name=kube_config_data_secret_name::KUBE_CONFIG_DATA_PRODUCTION"
        elif [[ "${{ github.ref }}" =~ ^refs/heads/staging ]]
        then
          echo "::set-output name=environment::staging"
          echo "::set-output name=namespace_prefix::ds-s"
        elif [[ "${{ github.ref }}" =~ ^refs/heads/develop ]]
        then
          echo "::set-output name=environment::develop"
          echo "::set-output name=namespace_prefix::ds-d"
          echo "::set-output name=k8s_ingress_base_host::development.api.daostats.io"
          echo "::set-output name=kube_config_data_secret_name::KUBE_CONFIG_DATA_DEVELOP"
        fi
        if [[ "${{ github.event.inputs.environment }}" != "" ]]
        then
          echo "input was provided: ${{ github.event.inputs.environment }}"
          echo "::set-output name=environment::${{ github.event.inputs.environment }}"
          echo "::set-output name=namespace_prefix::ds-d"
          echo "::set-output name=k8s_ingress_base_host::development.api.daostats.io"
          echo "::set-output name=kube_config_data_secret_name::KUBE_CONFIG_DATA_DEVELOP"
        fi

  build-image-aggregator:
    name: Build Image Aggregator
    env:
      APP_NAME: aggregator
    runs-on: ubuntu-latest
    needs:
    - get-environment
    environment:
      name: ${{ needs.get-environment.outputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
        echo DOCKER_ENV_TAG=${{ needs.get-environment.outputs.environment }}-$GITHUB_SHA >> $GITHUB_ENV
        cat ".github/env.common" | grep -E -v '^\ *#' >>$GITHUB_ENV
        cat ".github/env.${{ needs.get-environment.outputs.environment }}" | grep -E -v '^\ *#' >>$GITHUB_ENV
    - name: Docker Build Publish
      uses: ./.github/actions/docker-build-publish

  build-image-api:
    name: Build Image API
    env:
      APP_NAME: api
    runs-on: ubuntu-latest
    needs:
    - get-environment
    environment:
      name: ${{ needs.get-environment.outputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
        echo DOCKER_ENV_TAG=${{ needs.get-environment.outputs.environment }}-$GITHUB_SHA >> $GITHUB_ENV
        cat ".github/env.common" | grep -E -v '^\ *#' >>$GITHUB_ENV
        cat ".github/env.${{ needs.get-environment.outputs.environment }}" | grep -E -v '^\ *#' >>$GITHUB_ENV
    - name: Docker Build Publish
      uses: ./.github/actions/docker-build-publish

  helm-deploy-testnet:
    name: Helm Deploy Testnet
    runs-on: ubuntu-latest
    if: always()
    needs:
    - get-environment
    - build-image-aggregator
    - build-image-api
    environment:
      name: ${{ needs.get-environment.outputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
        echo DOCKER_ENV_TAG=${{ needs.get-environment.outputs.environment }}-$GITHUB_SHA >> $GITHUB_ENV
        cat ".github/env.common" | grep -E -v '^\ *#' >>$GITHUB_ENV
        cat ".github/env.${{ needs.get-environment.outputs.environment }}" | grep -E -v '^\ *#' >>$GITHUB_ENV
    - name: Helm Deploy
      uses: koslib/helm-eks-action@v1.8.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets[needs.get-environment.outputs.kube_config_data_secret_name] }}
      with:
        command: |
          set -x
          for APP_NAME in aggregator api
          do
            export CHART_FOLDER=apps/${APP_NAME}/deployment/app-chart
            helm lint $CHART_FOLDER
            helm -n ${{ needs.get-environment.outputs.namespace_prefix }}-testnet upgrade --install --create-namespace --atomic dao-stats-$APP_NAME $CHART_FOLDER \
              --set image.tag=$DOCKER_ENV_TAG \
              --set environment.contract_env=testnet \
              --set aggregatorConfig=${{ secrets.AGGREGATOR_CONFIG_TESTNET }} \
              --set ingress.host=testnet.${{ needs.get-environment.outputs.k8s_ingress_base_host }}
          done

  helm-deploy-mainnet:
    name: Helm Deploy Mainnet
    runs-on: ubuntu-latest
    if: always()
    needs:
    - get-environment
    - build-image-aggregator
    - build-image-api
    environment:
      name: ${{ needs.get-environment.outputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
        echo DOCKER_ENV_TAG=${{ needs.get-environment.outputs.environment }}-$GITHUB_SHA >> $GITHUB_ENV
        cat ".github/env.common" | grep -E -v '^\ *#' >>$GITHUB_ENV
        cat ".github/env.${{ needs.get-environment.outputs.environment }}" | grep -E -v '^\ *#' >>$GITHUB_ENV
    - name: Helm Deploy
      uses: koslib/helm-eks-action@v1.8.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets[needs.get-environment.outputs.kube_config_data_secret_name] }}
      with:
        command: |
          set -x
          for APP_NAME in aggregator api
          do
            export CHART_FOLDER=apps/${APP_NAME}/deployment/app-chart
            helm lint $CHART_FOLDER
            helm -n ${{ needs.get-environment.outputs.namespace_prefix }}-mainnet upgrade --install --create-namespace --atomic dao-stats-$APP_NAME $CHART_FOLDER \
              --set image.tag=$DOCKER_ENV_TAG \
              --set environment.contract_env=mainnet \
              --set aggregatorConfig=${{ secrets.AGGREGATOR_CONFIG_MAINNET }} \
              --set ingress.host=mainnet.${{ needs.get-environment.outputs.k8s_ingress_base_host }}
          done
