name: Test API
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
    paths:
      - '**'
      - '!apps/aggregator/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment
        run: |
          echo APP_NAME=api >> $GITHUB_ENV

      - name: Build Test
        uses: ./.github/actions/build-test
